## Build only, no tests are present ATM
version: "{build}"

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - git submodule init
  - git submodule update
  - cmake -H. -Bbuild -A%PLATFORM%


# build with MSBuild
build:
  project: build\pblib.sln              # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}
